#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres
HOME = $(shell echo $$HOME)

INC = -I$(HOME)/include
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = -L$(HOME)/lib
LIB = 
LDFLAGS = -lm -lgsl -lgslcblas

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -DDEBUG_MAIN -DSOBOL_RANDOM_SEQUENCE
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/DoubleLens

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -UDEBUG_MAIN -DINTEGRATE_PHOTON_PATH -DSOBOL_RANDOM_SEQUENCE
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/DoubleLens

INC_SOBOLINTEG = $(INC)
CFLAGS_SOBOLINTEG = $(CFLAGS) -O2 -UDEBUG_MAIN -DSOBOL_RANDOM_SEQUENCE -DINTEGRATE_PHOTON_PATH
RESINC_SOBOLINTEG = $(RESINC)
RCFLAGS_SOBOLINTEG = $(RCFLAGS)
LIBDIR_SOBOLINTEG = $(LIBDIR)
LIB_SOBOLINTEG = $(LIB)
LDFLAGS_SOBOLINTEG = $(LDFLAGS) -s
OBJDIR_SOBOLINTEG = obj/DoubleLensSobolInteg
DEP_SOBOLINTEG = 
OUT_SOBOLINTEG = bin/Release/DoubleLensSobolInteg

INC_SOBOLSIMPLE = $(INC)
CFLAGS_SOBOLSIMPLE = $(CFLAGS) -O2 -UDEBUG_MAIN -DSOBOL_RANDOM_SEQUENCE
RESINC_SOBOLSIMPLE = $(RESINC)
RCFLAGS_SOBOLSIMPLE = $(RCFLAGS)
LIBDIR_SOBOLSIMPLE = $(LIBDIR)
LIB_SOBOLSIMPLE = $(LIB)
LDFLAGS_SOBOLSIMPLE = $(LDFLAGS) -s
OBJDIR_SOBOLSIMPLE = obj/DoubleLensSobolSimple
DEP_SOBOLSIMPLE = 
OUT_SOBOLSIMPLE = bin/Release/DoubleLensSobolSimple

INC_RANDOMINTEG = $(INC)
CFLAGS_RANDOMINTEG = $(CFLAGS) -O2 -UDEBUG_MAIN -DINTEGRATE_PHOTON_PATH -DRANDOM_RAYS
RESINC_RANDOMINTEG = $(RESINC)
RCFLAGS_RANDOMINTEG = $(RCFLAGS)
LIBDIR_RANDOMINTEG = $(LIBDIR)
LIB_RANDOMINTEG = $(LIB)
LDFLAGS_RANDOMINTEG = $(LDFLAGS) -s
OBJDIR_RANDOMINTEG = obj/DoubleLensRandomInteg
DEP_RANDOMINTEG = 
OUT_RANDOMINTEG = bin/Release/DoubleLensRandomInteg

INC_RANDOMSIMPLE = $(INC)
CFLAGS_RANDOMSIMPLE = $(CFLAGS) -O2 -UDEBUG_MAIN -DRANDOM_RAYS
RESINC_RANDOMSIMPLE = $(RESINC)
RCFLAGS_RANDOMSIMPLE = $(RCFLAGS)
LIBDIR_RANDOMSIMPLE = $(LIBDIR)
LIB_RANDOMSIMPLE = $(LIB)
LDFLAGS_RANDOMSIMPLE = $(LDFLAGS) -s
OBJDIR_RANDOMSIMPLE = obj/DoubleLensRandomSimple
DEP_RANDOMSIMPLE = 
OUT_RANDOMSIMPLE = bin/Release/DoubleLensRandomSimple

OBJ_DEBUG = $(OBJDIR_DEBUG)/Test.o $(OBJDIR_DEBUG)/SourcePlaneGrid.o $(OBJDIR_DEBUG)/Main.o $(OBJDIR_DEBUG)/ML/Util.o $(OBJDIR_DEBUG)/ML/PolyCNumSolver.o $(OBJDIR_DEBUG)/InputRays.o $(OBJDIR_DEBUG)/GravLens.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/Test.o $(OBJDIR_RELEASE)/SourcePlaneGrid.o $(OBJDIR_RELEASE)/Main.o $(OBJDIR_RELEASE)/ML/Util.o $(OBJDIR_RELEASE)/ML/PolyCNumSolver.o $(OBJDIR_RELEASE)/InputRays.o $(OBJDIR_RELEASE)/GravLens.o

OBJ_SOBOLINTEG = $(OBJDIR_SOBOLINTEG)/Test.o $(OBJDIR_SOBOLINTEG)/SourcePlaneGrid.o $(OBJDIR_SOBOLINTEG)/Main.o $(OBJDIR_SOBOLINTEG)/ML/Util.o $(OBJDIR_SOBOLINTEG)/ML/PolyCNumSolver.o $(OBJDIR_SOBOLINTEG)/InputRays.o $(OBJDIR_SOBOLINTEG)/GravLens.o

OBJ_SOBOLSIMPLE = $(OBJDIR_SOBOLSIMPLE)/Test.o $(OBJDIR_SOBOLSIMPLE)/SourcePlaneGrid.o $(OBJDIR_SOBOLSIMPLE)/Main.o $(OBJDIR_SOBOLSIMPLE)/ML/Util.o $(OBJDIR_SOBOLSIMPLE)/ML/PolyCNumSolver.o $(OBJDIR_SOBOLSIMPLE)/InputRays.o $(OBJDIR_SOBOLSIMPLE)/GravLens.o

OBJ_RANDOMINTEG = $(OBJDIR_RANDOMINTEG)/Test.o $(OBJDIR_RANDOMINTEG)/SourcePlaneGrid.o $(OBJDIR_RANDOMINTEG)/Main.o $(OBJDIR_RANDOMINTEG)/ML/Util.o $(OBJDIR_RANDOMINTEG)/ML/PolyCNumSolver.o $(OBJDIR_RANDOMINTEG)/InputRays.o $(OBJDIR_RANDOMINTEG)/GravLens.o

OBJ_RANDOMSIMPLE = $(OBJDIR_RANDOMSIMPLE)/Test.o $(OBJDIR_RANDOMSIMPLE)/SourcePlaneGrid.o $(OBJDIR_RANDOMSIMPLE)/Main.o $(OBJDIR_RANDOMSIMPLE)/ML/Util.o $(OBJDIR_RANDOMSIMPLE)/ML/PolyCNumSolver.o $(OBJDIR_RANDOMSIMPLE)/InputRays.o $(OBJDIR_RANDOMSIMPLE)/GravLens.o

all: debug release sobolinteg sobolsimple randominteg randomsimple

clean: clean_debug clean_release clean_sobolinteg clean_sobolsimple clean_randominteg clean_randomsimple

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/ML || mkdir -p $(OBJDIR_DEBUG)/ML

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/Test.o: Test.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Test.cpp -o $(OBJDIR_DEBUG)/Test.o

$(OBJDIR_DEBUG)/SourcePlaneGrid.o: SourcePlaneGrid.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SourcePlaneGrid.cpp -o $(OBJDIR_DEBUG)/SourcePlaneGrid.o

$(OBJDIR_DEBUG)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Main.cpp -o $(OBJDIR_DEBUG)/Main.o

$(OBJDIR_DEBUG)/ML/Util.o: ML/Util.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ML/Util.cpp -o $(OBJDIR_DEBUG)/ML/Util.o

$(OBJDIR_DEBUG)/ML/PolyCNumSolver.o: ML/PolyCNumSolver.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ML/PolyCNumSolver.cpp -o $(OBJDIR_DEBUG)/ML/PolyCNumSolver.o

$(OBJDIR_DEBUG)/InputRays.o: InputRays.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c InputRays.cpp -o $(OBJDIR_DEBUG)/InputRays.o

$(OBJDIR_DEBUG)/GravLens.o: GravLens.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c GravLens.cpp -o $(OBJDIR_DEBUG)/GravLens.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/ML

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/ML || mkdir -p $(OBJDIR_RELEASE)/ML

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/Test.o: Test.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Test.cpp -o $(OBJDIR_RELEASE)/Test.o

$(OBJDIR_RELEASE)/SourcePlaneGrid.o: SourcePlaneGrid.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SourcePlaneGrid.cpp -o $(OBJDIR_RELEASE)/SourcePlaneGrid.o

$(OBJDIR_RELEASE)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Main.cpp -o $(OBJDIR_RELEASE)/Main.o

$(OBJDIR_RELEASE)/ML/Util.o: ML/Util.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ML/Util.cpp -o $(OBJDIR_RELEASE)/ML/Util.o

$(OBJDIR_RELEASE)/ML/PolyCNumSolver.o: ML/PolyCNumSolver.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ML/PolyCNumSolver.cpp -o $(OBJDIR_RELEASE)/ML/PolyCNumSolver.o

$(OBJDIR_RELEASE)/InputRays.o: InputRays.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c InputRays.cpp -o $(OBJDIR_RELEASE)/InputRays.o

$(OBJDIR_RELEASE)/GravLens.o: GravLens.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c GravLens.cpp -o $(OBJDIR_RELEASE)/GravLens.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/ML

before_sobolinteg: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_SOBOLINTEG) || mkdir -p $(OBJDIR_SOBOLINTEG)
	test -d $(OBJDIR_SOBOLINTEG)/ML || mkdir -p $(OBJDIR_SOBOLINTEG)/ML

after_sobolinteg: 

sobolinteg: before_sobolinteg out_sobolinteg after_sobolinteg

out_sobolinteg: before_sobolinteg $(OBJ_SOBOLINTEG) $(DEP_SOBOLINTEG)
	$(LD) $(LIBDIR_SOBOLINTEG) -o $(OUT_SOBOLINTEG) $(OBJ_SOBOLINTEG)  $(LDFLAGS_SOBOLINTEG) $(LIB_SOBOLINTEG)

$(OBJDIR_SOBOLINTEG)/Test.o: Test.cpp
	$(CXX) $(CFLAGS_SOBOLINTEG) $(INC_SOBOLINTEG) -c Test.cpp -o $(OBJDIR_SOBOLINTEG)/Test.o

$(OBJDIR_SOBOLINTEG)/SourcePlaneGrid.o: SourcePlaneGrid.cpp
	$(CXX) $(CFLAGS_SOBOLINTEG) $(INC_SOBOLINTEG) -c SourcePlaneGrid.cpp -o $(OBJDIR_SOBOLINTEG)/SourcePlaneGrid.o

$(OBJDIR_SOBOLINTEG)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_SOBOLINTEG) $(INC_SOBOLINTEG) -c Main.cpp -o $(OBJDIR_SOBOLINTEG)/Main.o

$(OBJDIR_SOBOLINTEG)/ML/Util.o: ML/Util.cpp
	$(CXX) $(CFLAGS_SOBOLINTEG) $(INC_SOBOLINTEG) -c ML/Util.cpp -o $(OBJDIR_SOBOLINTEG)/ML/Util.o

$(OBJDIR_SOBOLINTEG)/ML/PolyCNumSolver.o: ML/PolyCNumSolver.cpp
	$(CXX) $(CFLAGS_SOBOLINTEG) $(INC_SOBOLINTEG) -c ML/PolyCNumSolver.cpp -o $(OBJDIR_SOBOLINTEG)/ML/PolyCNumSolver.o

$(OBJDIR_SOBOLINTEG)/InputRays.o: InputRays.cpp
	$(CXX) $(CFLAGS_SOBOLINTEG) $(INC_SOBOLINTEG) -c InputRays.cpp -o $(OBJDIR_SOBOLINTEG)/InputRays.o

$(OBJDIR_SOBOLINTEG)/GravLens.o: GravLens.cpp
	$(CXX) $(CFLAGS_SOBOLINTEG) $(INC_SOBOLINTEG) -c GravLens.cpp -o $(OBJDIR_SOBOLINTEG)/GravLens.o

clean_sobolinteg: 
	rm -f $(OBJ_SOBOLINTEG) $(OUT_SOBOLINTEG)
	rm -rf bin/Release
	rm -rf $(OBJDIR_SOBOLINTEG)
	rm -rf $(OBJDIR_SOBOLINTEG)/ML

before_sobolsimple: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_SOBOLSIMPLE) || mkdir -p $(OBJDIR_SOBOLSIMPLE)
	test -d $(OBJDIR_SOBOLSIMPLE)/ML || mkdir -p $(OBJDIR_SOBOLSIMPLE)/ML

after_sobolsimple: 

sobolsimple: before_sobolsimple out_sobolsimple after_sobolsimple

out_sobolsimple: before_sobolsimple $(OBJ_SOBOLSIMPLE) $(DEP_SOBOLSIMPLE)
	$(LD) $(LIBDIR_SOBOLSIMPLE) -o $(OUT_SOBOLSIMPLE) $(OBJ_SOBOLSIMPLE)  $(LDFLAGS_SOBOLSIMPLE) $(LIB_SOBOLSIMPLE)

$(OBJDIR_SOBOLSIMPLE)/Test.o: Test.cpp
	$(CXX) $(CFLAGS_SOBOLSIMPLE) $(INC_SOBOLSIMPLE) -c Test.cpp -o $(OBJDIR_SOBOLSIMPLE)/Test.o

$(OBJDIR_SOBOLSIMPLE)/SourcePlaneGrid.o: SourcePlaneGrid.cpp
	$(CXX) $(CFLAGS_SOBOLSIMPLE) $(INC_SOBOLSIMPLE) -c SourcePlaneGrid.cpp -o $(OBJDIR_SOBOLSIMPLE)/SourcePlaneGrid.o

$(OBJDIR_SOBOLSIMPLE)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_SOBOLSIMPLE) $(INC_SOBOLSIMPLE) -c Main.cpp -o $(OBJDIR_SOBOLSIMPLE)/Main.o

$(OBJDIR_SOBOLSIMPLE)/ML/Util.o: ML/Util.cpp
	$(CXX) $(CFLAGS_SOBOLSIMPLE) $(INC_SOBOLSIMPLE) -c ML/Util.cpp -o $(OBJDIR_SOBOLSIMPLE)/ML/Util.o

$(OBJDIR_SOBOLSIMPLE)/ML/PolyCNumSolver.o: ML/PolyCNumSolver.cpp
	$(CXX) $(CFLAGS_SOBOLSIMPLE) $(INC_SOBOLSIMPLE) -c ML/PolyCNumSolver.cpp -o $(OBJDIR_SOBOLSIMPLE)/ML/PolyCNumSolver.o

$(OBJDIR_SOBOLSIMPLE)/InputRays.o: InputRays.cpp
	$(CXX) $(CFLAGS_SOBOLSIMPLE) $(INC_SOBOLSIMPLE) -c InputRays.cpp -o $(OBJDIR_SOBOLSIMPLE)/InputRays.o

$(OBJDIR_SOBOLSIMPLE)/GravLens.o: GravLens.cpp
	$(CXX) $(CFLAGS_SOBOLSIMPLE) $(INC_SOBOLSIMPLE) -c GravLens.cpp -o $(OBJDIR_SOBOLSIMPLE)/GravLens.o

clean_sobolsimple: 
	rm -f $(OBJ_SOBOLSIMPLE) $(OUT_SOBOLSIMPLE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_SOBOLSIMPLE)
	rm -rf $(OBJDIR_SOBOLSIMPLE)/ML

before_randominteg: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RANDOMINTEG) || mkdir -p $(OBJDIR_RANDOMINTEG)
	test -d $(OBJDIR_RANDOMINTEG)/ML || mkdir -p $(OBJDIR_RANDOMINTEG)/ML

after_randominteg: 

randominteg: before_randominteg out_randominteg after_randominteg

out_randominteg: before_randominteg $(OBJ_RANDOMINTEG) $(DEP_RANDOMINTEG)
	$(LD) $(LIBDIR_RANDOMINTEG) -o $(OUT_RANDOMINTEG) $(OBJ_RANDOMINTEG)  $(LDFLAGS_RANDOMINTEG) $(LIB_RANDOMINTEG)

$(OBJDIR_RANDOMINTEG)/Test.o: Test.cpp
	$(CXX) $(CFLAGS_RANDOMINTEG) $(INC_RANDOMINTEG) -c Test.cpp -o $(OBJDIR_RANDOMINTEG)/Test.o

$(OBJDIR_RANDOMINTEG)/SourcePlaneGrid.o: SourcePlaneGrid.cpp
	$(CXX) $(CFLAGS_RANDOMINTEG) $(INC_RANDOMINTEG) -c SourcePlaneGrid.cpp -o $(OBJDIR_RANDOMINTEG)/SourcePlaneGrid.o

$(OBJDIR_RANDOMINTEG)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_RANDOMINTEG) $(INC_RANDOMINTEG) -c Main.cpp -o $(OBJDIR_RANDOMINTEG)/Main.o

$(OBJDIR_RANDOMINTEG)/ML/Util.o: ML/Util.cpp
	$(CXX) $(CFLAGS_RANDOMINTEG) $(INC_RANDOMINTEG) -c ML/Util.cpp -o $(OBJDIR_RANDOMINTEG)/ML/Util.o

$(OBJDIR_RANDOMINTEG)/ML/PolyCNumSolver.o: ML/PolyCNumSolver.cpp
	$(CXX) $(CFLAGS_RANDOMINTEG) $(INC_RANDOMINTEG) -c ML/PolyCNumSolver.cpp -o $(OBJDIR_RANDOMINTEG)/ML/PolyCNumSolver.o

$(OBJDIR_RANDOMINTEG)/InputRays.o: InputRays.cpp
	$(CXX) $(CFLAGS_RANDOMINTEG) $(INC_RANDOMINTEG) -c InputRays.cpp -o $(OBJDIR_RANDOMINTEG)/InputRays.o

$(OBJDIR_RANDOMINTEG)/GravLens.o: GravLens.cpp
	$(CXX) $(CFLAGS_RANDOMINTEG) $(INC_RANDOMINTEG) -c GravLens.cpp -o $(OBJDIR_RANDOMINTEG)/GravLens.o

clean_randominteg: 
	rm -f $(OBJ_RANDOMINTEG) $(OUT_RANDOMINTEG)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RANDOMINTEG)
	rm -rf $(OBJDIR_RANDOMINTEG)/ML

before_randomsimple: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RANDOMSIMPLE) || mkdir -p $(OBJDIR_RANDOMSIMPLE)
	test -d $(OBJDIR_RANDOMSIMPLE)/ML || mkdir -p $(OBJDIR_RANDOMSIMPLE)/ML

after_randomsimple: 

randomsimple: before_randomsimple out_randomsimple after_randomsimple

out_randomsimple: before_randomsimple $(OBJ_RANDOMSIMPLE) $(DEP_RANDOMSIMPLE)
	$(LD) $(LIBDIR_RANDOMSIMPLE) -o $(OUT_RANDOMSIMPLE) $(OBJ_RANDOMSIMPLE)  $(LDFLAGS_RANDOMSIMPLE) $(LIB_RANDOMSIMPLE)

$(OBJDIR_RANDOMSIMPLE)/Test.o: Test.cpp
	$(CXX) $(CFLAGS_RANDOMSIMPLE) $(INC_RANDOMSIMPLE) -c Test.cpp -o $(OBJDIR_RANDOMSIMPLE)/Test.o

$(OBJDIR_RANDOMSIMPLE)/SourcePlaneGrid.o: SourcePlaneGrid.cpp
	$(CXX) $(CFLAGS_RANDOMSIMPLE) $(INC_RANDOMSIMPLE) -c SourcePlaneGrid.cpp -o $(OBJDIR_RANDOMSIMPLE)/SourcePlaneGrid.o

$(OBJDIR_RANDOMSIMPLE)/Main.o: Main.cpp
	$(CXX) $(CFLAGS_RANDOMSIMPLE) $(INC_RANDOMSIMPLE) -c Main.cpp -o $(OBJDIR_RANDOMSIMPLE)/Main.o

$(OBJDIR_RANDOMSIMPLE)/ML/Util.o: ML/Util.cpp
	$(CXX) $(CFLAGS_RANDOMSIMPLE) $(INC_RANDOMSIMPLE) -c ML/Util.cpp -o $(OBJDIR_RANDOMSIMPLE)/ML/Util.o

$(OBJDIR_RANDOMSIMPLE)/ML/PolyCNumSolver.o: ML/PolyCNumSolver.cpp
	$(CXX) $(CFLAGS_RANDOMSIMPLE) $(INC_RANDOMSIMPLE) -c ML/PolyCNumSolver.cpp -o $(OBJDIR_RANDOMSIMPLE)/ML/PolyCNumSolver.o

$(OBJDIR_RANDOMSIMPLE)/InputRays.o: InputRays.cpp
	$(CXX) $(CFLAGS_RANDOMSIMPLE) $(INC_RANDOMSIMPLE) -c InputRays.cpp -o $(OBJDIR_RANDOMSIMPLE)/InputRays.o

$(OBJDIR_RANDOMSIMPLE)/GravLens.o: GravLens.cpp
	$(CXX) $(CFLAGS_RANDOMSIMPLE) $(INC_RANDOMSIMPLE) -c GravLens.cpp -o $(OBJDIR_RANDOMSIMPLE)/GravLens.o

clean_randomsimple: 
	rm -f $(OBJ_RANDOMSIMPLE) $(OUT_RANDOMSIMPLE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RANDOMSIMPLE)
	rm -rf $(OBJDIR_RANDOMSIMPLE)/ML

virtual_all: debug release sobolinteg sobolsimple randominteg randomsimple

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release before_sobolinteg after_sobolinteg clean_sobolinteg before_sobolsimple after_sobolsimple clean_sobolsimple before_randominteg after_randominteg clean_randominteg before_randomsimple after_randomsimple clean_randomsimple

